version: "3"
services:
  vmb:
    # image: "534003348933.dkr.ecr.eu-west-1.amazonaws.com/verify-my-ballot:main"
    image: "verify-my-ballot:latest"
    build: "."
    command: "yarn start"
    ports:
      - "3005:3005"
    volumes:
      - "./:/usr/src/app"
      - "/usr/src/app/node_modules"
    environment:
      REACT_APP_BASE_ELECTION_URL: "http://localhost:3003"
      REACT_APP_TIMEOUT_REMINDER_TIME: 60
      REACT_APP_TIMEOUT_RETRIES: 100
      REACT_APP_STRICT: false
