name: Tests
on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize
  push:
    branches:
      - 'master'
jobs:
  cypress-run:
    name: End-to-end tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          start: yarn start-test
          wait-on: 'http://localhost:3005'
          wait-on-timeout: 180
          browser: chrome
          headless: true
      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: screenshots
          path: cypress/screenshots
